# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_ACCESS_TOKEN: ${{ secrets.FIREBASE_ACCESS_TOKEN }}
      STORAGE_BUCKET_URL: ${{ secrets.STORAGE_BUCKET_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Setup Python and Execute
      - run: python ./scripts/main.py
