# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      FIREBASE_ACCESS_TOKEN: ${{ secrets.FIREBASE_ACCESS_TOKEN }}
      STORAGE_BUCKET_URL: ${{ secrets.STORAGE_BUCKET_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Setup pip
        uses: BSFishy/pip-action@v1
        with:
          packages: firebase_admin
      - name: Setup Python and Execute
        run: echo $FIREBASE_ACCESS_TOKEN >> ./scripts/wr6yghttcx9.json && python ./scripts/main.py
